### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by tharvik** [c4dt/angular-components#10]
When #9 is merged, do a NPM release so that @cgrigis can depend on a stable `c4dt.css`.

**Comment by cgrigis** [comment]
More than me, it's the showcase that will depend on it :laughing:

**Comment by ineiti** [comment]
How to hack @cgrigis: change the c4dt.css...

**Comment by cgrigis** [comment]
> How to hack @cgrigis: change the c4dt.css...

Don't change my dark mode! :smile:

**Comment by ineiti** [comment]
Couldn't we give you a pink shirt and a green trouser with a css? That would be a real-life hack!

**Comment by cgrigis** [comment]
:scream:

**Comment by tharvik** [comment]
`@c4dt/angular-components-3.0.0` published, have fun with it :)
