### ISSUE TITLE
add C4DT styles

### ISSUE THREAD

**Issue by tharvik** [c4dt/angular-components#8]
It would be very nice to have a common stylesheet for C4DT angular apps. The trick is to have an asset that gets loaded by every app, as shown in https://github.com/c4dt/angular-components/commit/fb40ddfaec7417ef2a76bbc9b0c4888e40646890.

Then, each app can use it by adding `@import "@c4dt/angular-components/src/c4dt.css";` to its `src/styles.css`.

@LucasTrg please do so, a small PR in angular-components with the shared style, when merged, you can udpate each app using it (so service-spindle & service-stainless for now).

If you want to test locally the changes you implement, you can use `npm i ../../path/to/your/angular-components/dist/lib` after an `npx ng build`.

**Comment by LucasTrg** [comment]
I managed to get the build process to work after some time, I've made a very basic stylesheet and tested it on spindle. I'm ready to issue a PR so we can further discuss the specs of the stylecheets ! I don't have write access to the repo yet however

**Comment by tharvik** [comment]
> I managed to get the build process to work after some time, I've made a very basic stylesheet and tested it on spindle. I'm ready to issue a PR so we can further discuss the specs of the stylecheets !

Perfect!

> I don't have write access to the repo yet however

Ho, right, I always forget to do that, you should be able to create branches & PR now.
